## Text noun phrase classifier

In [1]:
import jsonlines
import tqdm
import json
import spacy
import numpy as np 
import pandas as pd
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

# import scispacy
import spacy
# import en_core_web_sm

from scipy.spatial.distance import jensenshannon

import joblib

from IPython.display import HTML, display

from ipywidgets import interact, Layout, HBox, VBox, Box
import ipywidgets as widgets
from IPython.display import clear_output

from tqdm import tqdm
from os.path import isfile

import seaborn as sb
import matplotlib.pyplot as plt
plt.style.use("dark_background")
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from tqdm import tqdm
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer 
from nltk.tokenize import word_tokenize

from multiprocessing import Pool

import os, re, csv, math, codecs
from sklearn.model_selection import train_test_split
sns.set_style("whitegrid")
np.random.seed(0)

os.environ["CUDA_VISIBLE_DEVICES"]="1"

stop_words = set(stopwords.words('english'))
stop_words.update(['.', ',', '"', "'", ':', ';', '(', ')', '[', ']', '{', '}'])
# DATA_PATH = '/data/szr207/projects/log_analysis/equal_scidocs.csv'

from subprocess import check_output
# print(check_output(["ls", DATA_PATH]).decode("utf8"))
# plt.style.use("dark_background")

# DATA_PATH = '/data/szr207/dataset/scidocs/mag/combined.csv'

2023-01-29 17:57:33.563646: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-01-29 17:57:35.507963: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-01-29 17:57:35.508069: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2023-01-29 17:57:35.508608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:1d:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.77GiB deviceMemoryBandwidth: 836.37GiB/s
2023-01-29 17:57:35.508636: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-01-29 17:57:35.510989: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2023-01-29 17:57:35.511075: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2023-01-29 17:57:35.513298: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2023-01-29 17:57:35.513726: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2023-01-29 17:57:35.516184: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2023-01-29 17:57:35.517594: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2023-01-29 17:57:35.522908: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2023-01-29 17:57:35.523750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)

- number of tokens
- number of capital letters
- number of special characters
- consecutive punctuation marks
- percent of stop-words in text 
- min document freq
- max DF
- median document freq

In [2]:
df_data = pd.read_csv('noun_title_classification.csv')

In [3]:
df_data['doc_len'] = df_data['text'].apply(lambda words: len(word_tokenize(str(words))))


max_seq_len = 41
sns.distplot(df_data['doc_len'], hist=True, kde=True, color='b', label='doc len')
plt.axvline(x=max_seq_len, color='k', linestyle='--', label='max len')
plt.title('comment length'); plt.legend()
plt.show()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  """
/opt/conda/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:1402: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  ndim = x[:, None].ndim
/opt/conda/lib/python3.7/site-packages/matplotlib/axes/_base.py:276: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  x = x[:, np.newaxis]
/opt/conda/lib/python3.7/site-packages/matplotlib/axes/_base.py:278: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  y = y[:, np.newaxis]

In [4]:
# number of capital letters

def get_capital_count(x):
    count = 0
    for i in word_tokenize(str(x)):
        if i.isupper():
            count+=1
    return count

In [5]:
df_data['upper_count'] = df_data['text'].apply(lambda x:get_capital_count(x))

In [6]:
df_data

,text,label,doc_len,upper_count
0,they,np,1,0
1,PhD training in simulation: NATCOR,title,6,1
2,Effect of SLCO1B1 Polymorphisms on Rifabutin P...,title,14,1
3,methodology,np,1,0
4,A randomized controlled trial of the efficacy ...,title,34,1
...,...,...,...,...
96941,Profitability of Canadian- Versus U.S.-control...,title,6,0
96942,neutropenia,np,1,0
96943,"Multidisciplinary Essays. (Book Reviews: Mind,...",title,25,0
96944,Major bleeding,np,2,0
96945,Efficacy and Feasibility of Functional Upper E...,title,18,0

In [7]:
df_data['upper_count']

0        0
1        1
2        1
3        0
4        1
        ..
96941    0
96942    0
96943    0
96944    0
96945    0
Name: upper_count, Length: 96946, dtype: int64

In [8]:
from string import punctuation

def get_punctuation_counts(x):
    punctuation_counts = 0
    for i in word_tokenize(str(x)):
        if i in punctuation:
            punctuation_counts+=1
    return punctuation_counts

In [9]:
def stop_word_count(x):
    stop_count = 0
    for i in word_tokenize(str(x)):
        if i in stop_words:
            stop_count+=1
    return stop_count

In [10]:
get_punctuation_counts('PhD training in simulation: NATCOR')

1

In [11]:
df_data

,text,label,doc_len,upper_count
0,they,np,1,0
1,PhD training in simulation: NATCOR,title,6,1
2,Effect of SLCO1B1 Polymorphisms on Rifabutin P...,title,14,1
3,methodology,np,1,0
4,A randomized controlled trial of the efficacy ...,title,34,1
...,...,...,...,...
96941,Profitability of Canadian- Versus U.S.-control...,title,6,0
96942,neutropenia,np,1,0
96943,"Multidisciplinary Essays. (Book Reviews: Mind,...",title,25,0
96944,Major bleeding,np,2,0
96945,Efficacy and Feasibility of Functional Upper E...,title,18,0

In [12]:
df_data['punct_count'] = df_data['text'].apply(lambda x:get_punctuation_counts(x))

In [13]:
df_data['stop_count'] = df_data['text'].apply(lambda x:stop_word_count(x))

In [14]:
df_data = df_data.dropna()

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

path_sci = 'sci_dump.txt'

with open(path_sci) as f:
    text_lines = f.read().splitlines()

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=50000)
X = vectorizer.fit_transform(text_lines)
# print(vectorizer.get_feature_names())

# print(X.shape)

In [17]:
df_data = df_data.dropna().reset_index(drop=True)

In [18]:
tf_idf = vectorizer.transform(df_data['text'])

In [19]:
df_data.shape

(96944, 6)

In [20]:
a = tf_idf[1].toarray()[0]

In [21]:
import numpy as np

minval = np.min(a[np.nonzero(a)])
maxval = np.max(a[np.nonzero(a)])
median = np.median(a[np.nonzero(a)])

In [22]:
maxval

0.7409509708429297

In [23]:
median

0.46856287260010354

In [24]:
minval

0.10559593437062544

In [25]:
min_list = []
max_list = []
med_list = []

for i in tqdm(tf_idf):
    a = i.toarray()[0]
    try:
        min_list.append(np.min(a[np.nonzero(a)]))
        max_list.append(np.max(a[np.nonzero(a)]))
        med_list.append(np.median(a[np.nonzero(a)]))
    except:
        min_list.append(0.0)
        max_list.append(0.0)
        med_list.append(0.0)

96944it [02:48, 576.33it/s]

In [26]:
max_list

[1.0,
 0.7409509708429297,
 0.4454618668273191,
 1.0,
 0.3808892603509144,
 0.506178997810789,
 0.37918548619103043,
 0.5209875467452301,
 1.0,
 0.4105259083571916,
 0.4553198673516652,
 0.9877428014306799,
 0.4063911808920798,
 0.7349530368142965,
 1.0,
 0.5022559557523124,
 0.42586952215583757,
 1.0,
 0.46281691029153726,
 1.0,
 1.0,
 0.6040228295559257,
 1.0,
 0.6945391010772781,
 0.5457375750489417,
 0.4152443250124351,
 0.5234370751010409,
 0.5148706058989336,
 1.0,
 0.4189216052878228,
 0.776445338477066,
 1.0,
 0.5265585890989474,
 0.7619097582645955,
 0.8727874139322936,
 0.8314622213679533,
 1.0,
 0.5435898335896531,
 0.6581636320067723,
 0.7266266923791006,
 1.0,
 0.5408300022139203,
 0.48226327702706295,
 1.0,
 0.5686814160641912,
 0.4889343747996727,
 1.0,
 1.0,
 0.7634582840709473,
 0.6986393347515628,
 0.41003769920174454,
 0.796849186766923,
 0.6371707132389685,
 0.7972653621635752,
 0.5886735344347002,
 0.41681809694995486,
 0.6565781444546153,
 1.0,
 0.5097914373625645,
 0.8597738912559737,
 0.7982113264538667,
 0.9113016442274835,
 0.7711252102418543,
 0.6862701113779984,
 0.5781586851797584,
 0.4735453660421122,
 0.4335496898832468,
 0.7732545186484802,
 0.47344991522736996,
 0.0,
 0.5421806446608514,
 0.6357101826734457,
 0.8399284506466487,
 0.5026346269066823,
 1.0,
 0.6170425431828747,
 0.6632596673357853,
 0.5840657446670532,
 1.0,
 0.9155860510823087,
 1.0,
 1.0,
 0.6045558104892488,
 0.501188547116395,
 0.47734292252105487,
 0.49417793069575816,
 0.5404756677549971,
 0.9589556571523813,
 1.0,
 0.480190375718877,
 1.0,
 0.6806676399787106,
 0.7803952864447504,
 0.5707796007292257,
 0.4675200931773766,
 0.0,
 0.5623976242896814,
 0.9676439474923589,
 0.47781327062198603,
 0.4274300302019685,
 0.3697055061212573,
 0.7214245111447984,
 0.562582270004497,
 0.8248480674125196,
 0.0,
 0.4697593498865621,
 0.5303793482644603,
 1.0,
 0.6267356642216122,
 0.7706515060267497,
 0.8618201416510161,
 0.414925020313909,
 0.6125215962470274,
 0.4333739651608902,
 0.7191822951730805,
 0.7724042112386178,
 0.6881600696985201,
 0.9457761377994606,
 0.49526570215812643,
 0.9161255370546978,
 0.3881988517276942,
 0.4954271036069209,
 0.7855355684871015,
 0.393421456602071,
 0.643693734898573,
 0.5268988175465059,
 0.6763490226822794,
 0.8334796766284414,
 0.5385004198542163,
 0.5913410483379138,
 0.4069412153755695,
 0.4638103546803351,
 1.0,
 0.3630071937398661,
 0.4678966928165982,
 0.9457761377994606,
 0.5222520408178831,
 0.995193055820505,
 0.42713839659274544,
 0.8741605891521664,
 0.5151400097256716,
 1.0,
 0.47221623846074523,
 1.0,
 0.7346576268082031,
 1.0,
 0.4633623238117033,
 0.7510106242501271,
 0.0,
 0.5709648981160779,
 0.9741767946462337,
 0.49238660958710817,
 0.36524512515423685,
 0.9214517467307476,
 1.0,
 0.8848083407618669,
 0.6831366128675592,
 0.40763405910918943,
 0.4938583701065272,
 0.470834789266899,
 0.4771671263319717,
 0.0,
 0.927020340806991,
 0.4623474806219753,
 1.0,
 0.8033211683256015,
 0.0,
 0.42825318967317205,
 1.0,
 0.6707872846287622,
 0.6427390771968419,
 1.0,
 0.44402788900119883,
 0.9587351633315203,
 0.7673053077498913,
 0.5170498847525704,
 1.0,
 1.0,
 1.0,
 0.7217470613352677,
 0.49052659916842706,
 0.5457212774108872,
 0.4888832423250522,
 0.48904388170441826,
 0.5093879057952576,
 0.4482110633016172,
 0.5824519814493145,
 1.0,
 1.0,
 0.8349361417208856,
 1.0,
 1.0,
 0.8386394940661567,
 1.0,
 0.6799809487439065,
 0.9854198111028443,
 0.5518516930317644,
 1.0,
 0.5016290194035014,
 0.6087681785303212,
 0.7420742116475069,
 0.7409459772334716,
 0.8962556346452647,
 0.7911687832206773,
 0.9393135831716016,
 0.5962063423205767,
 0.6006393672728634,
 0.4418289930355145,
 0.5244007454180977,
 1.0,
 0.41681561123407845,
 0.5388878557568901,
 1.0,
 0.0,
 0.5719140037744597,
 0.9711084454510448,
 0.4404430887934891,
 0.9860693018770395,
 0.6456387854596214,
 0.8154487254533725,
 0.3320329340759209,
 0.502630700182519,
 0.537240236126482,
 0.977624491306987,
 1.0,
 0.7194062998050291,
 0.350925013359678,
 0.4321917697586907,
 0.9753831086382503,
 0.8693221006667462,
 1.0,
 0.9575399266577765,
 1.0,
 0.4553596933097677,
 0.7914993657069256,
 1.0,
 1.0,
 0.3558832291494248,
 0.3862862530521116,
 0.5959698527377163,
 1.0,
 0.5327201778854774,
 0.7634250081894232,
 0.5505539396563022,
 0.419844638126957,
 0.7508452310197058,
 1.0,
 0.9809488522712853,
 0.395656837402354,
 0.8662661672327724,
 0.7454241471818495,
 0.0,
 0.9682316333517581,
 0.8262265073359996,
 0.5783915852851343,
 0.4233312755252267,
 0.7791551286222043,
 0.37953254831728517,
 0.46420388122974043,
 0.5578816722489478,
 0.43585333862603154,
 0.516658530360395,
 0.8780978009055483,
 1.0,
 0.5285576117240108,
 0.630015048480604,
 0.5011326722626259,
 0.7346914224459354,
 1.0,
 0.5032738488136642,
 0.4744427435896708,
 0.8936854333848354,
 0.5586208995332458,
 0.8419936172033144,
 0.8579445261983611,
 1.0,
 0.0,
 0.751935395494094,
 1.0,
 0.8217351779232883,
 0.4187986637172877,
 0.7300972102254889,
 0.9010189080058479,
 0.37119291667549975,
 1.0,
 0.5409494690019887,
 0.5907816882101548,
 1.0,
 0.6621403735436484,
 1.0,
 1.0,
 1.0,
 0.4523547018659127,
 1.0,
 0.6330136463734777,
 1.0,
 0.4872857815596808,
 0.9878576086457695,
 1.0,
 0.0,
 0.5600099705142141,
 0.7283764846686029,
 1.0,
 0.5173237825505214,
 0.8450186833109142,
 0.9907290768397105,
 0.8439219964648684,
 0.5103331406661259,
 0.42927522284902175,
 0.41434279670047997,
 0.5764314666641783,
 0.9822219751587437,
 0.6959249312274907,
 0.4402028700105361,
 0.4810813539420035,
 0.5210995568011728,
 0.6211435961243725,
 0.6220929665012099,
 0.9665233264040405,
 1.0,
 0.8711691596675661,
 0.8850177715506515,
 0.6107141522342544,
 0.6122187591393907,
 0.6635732913687303,
 0.8319442259540935,
 1.0,
 0.48005310173216514,
 0.5632101086351169,
 0.8561515806712345,
 0.4693156142234512,
 0.7807263833392522,
 0.6091160953879818,
 1.0,
 0.8246434582374536,
 1.0,
 0.832617040706358,
 0.5286382279901103,
 0.3923039810488855,
 0.5096582901452167,
 0.9782291997348885,
 0.5357846646205178,
 0.6383773247215502,
 0.5263304322460916,
 0.4012453547715788,
 0.48577645231619027,
 0.6060538702388822,
 0.7017551520009919,
 1.0,
 0.4895582369060009,
 0.591521556949594,
 0.9605356870273689,
 0.67085235501154,
 0.44915588197161693,
 0.42922138343895977,
 0.4840950041899821,
 0.6386965642454373,
 0.41576405883906,
 0.6400205373416822,
 0.7638359757462165,
 0.39890175453815085,
 0.41742219525759244,
 0.5187426716033827,
 1.0,
 0.7732105486979215,
 0.47115989881006404,
 1.0,
 0.8283605508760922,
 0.6452044375323331,
 1.0,
 0.6513835871199521,
 0.0,
 0.8044935431372661,
 0.9841094269378388,
 0.6098675051300049,
 0.4625640037754332,
 0.39587803163643054,
 0.6766475631113206,
 0.7276546838925118,
 0.7546767490922858,
 0.9412109983108898,
 0.43975218912716507,
 1.0,
 0.9053984182445509,
 0.5499876502951795,
 0.8198044391709947,
 0.423390784878347,
 0.5427615685512083,
 0.8678225622568757,
 0.46382545601003283,
 0.5257449687183998,
 0.8848370082333753,
 0.6144910720039308,
 0.6944471579284268,
 0.5947188960310862,
 0.5086472071711629,
 0.39994719929225975,
 0.5698578956029743,
 0.9592666182721773,
 1.0,
 1.0,
 0.3951390622412345,
 0.9659079153787183,
 1.0,
 1.0,
 0.6833700289119289,
 0.6393021865767219,
 0.5152800187629868,
 1.0,
 0.5588260767645342,
 0.465729278779509,
 0.39935588330173954,
 0.8841919365996221,
 0.5298750589147764,
 1.0,
 0.48578339210138705,
 0.41101732277809233,
 0.6676733448940103,
 0.8310227463336847,
 1.0,
 0.3230137012519829,
 0.3544687140176448,
 0.6688394691420261,
 0.560023767972509,
 0.9445667664482728,
 0.5490430961046503,
 1.0,
 0.8129591961799776,
 1.0,
 0.9329819306382796,
 0.7971425344712406,
 0.6708988086777247,
 0.6258813006083219,
 0.4833845549171449,
 0.36531088850587184,
 0.526342215237749,
 0.5820961468850658,
 0.46074089548625846,
 0.7181732015264904,
 1.0,
 0.394533126872441,
 0.6727474969639549,
 0.8298621799783615,
 0.5613657290128576,
 0.8365875561440141,
 0.7428612654745427,
 0.38541237528195954,
 1.0,
 0.4645737898171099,
 0.4472776201641923,
 0.5519561639913088,
 0.7331681680883934,
 1.0,
 0.7588626295760664,
 1.0,
 0.503496543600529,
 0.4654978483199747,
 0.5369245668200083,
 0.3759377348909349,
 1.0,
 0.4097627158559108,
 0.383274395265127,
 0.45833542930060317,
 0.3439565226766658,
 0.35871949353874194,
 0.8133713125397528,
 0.7590921841549867,
 0.5618115956805979,
 0.5930672780812913,
 0.5491324060233045,
 0.881739194808847,
 1.0,
 0.3327816604101111,
 0.46084710972138143,
 0.5266681775531905,
 0.6281127359247993,
 0.53831240360817,
 0.46770542019519634,
 0.8982760254669204,
 0.9682316333517581,
 0.0,
 0.811368813272167,
 0.7393204340489935,
 0.5012593622692417,
 0.6648394367204421,
 0.0,
 0.4909712280689979,
 0.8721113947454397,
 0.5795982771146031,
 0.8258819758374228,
 0.7865143771635692,
 0.46686955759723325,
 0.4749151539051477,
 0.5555925670097784,
 0.5955618139524483,
 0.5556645158158765,
 0.41306512177183696,
 0.0,
 1.0,
 0.30650529325376197,
 0.5870275209806117,
 0.9763742104968627,
 0.40112143575122644,
 0.49369383699692904,
 0.7347143782347222,
 0.5739550926566648,
 0.6561334771097065,
 0.44604511763893445,
 0.6025010985824891,
 0.5546471893185155,
 0.8580158724717983,
 0.0,
 0.5569496096838913,
 0.9936327646128191,
 0.5389879443449214,
 0.5220850859308179,
 1.0,
 0.9553443217249151,
 0.0,
 0.0,
 0.6325175471080454,
 0.690659703642159,
 0.8618716912220116,
 0.7910161252277415,
 1.0,
 0.42156433744029587,
 0.48366996286888625,
 0.47703154318376395,
 0.6893685027080761,
 0.46584877190602203,
 1.0,
 0.7700995267210039,
 1.0,
 0.4985826656418667,
 0.8607079560161449,
 0.6100133940938881,
 0.8433970864425517,
 0.9925474416821854,
 0.5146061968465142,
 0.979475291053581,
 1.0,
 0.7725222598282381,
 0.0,
 0.5502916992418754,
 0.9865225922163394,
 0.6979637289207314,
 0.6720530881293973,
 0.7206837248328901,
 0.430439943022686,
 1.0,
 0.6338568912786658,
 0.5858642334562381,
 0.6824600358465432,
 0.3579149256510858,
 0.8099421488647368,
 0.8262685560136168,
 0.6683957700905907,
 0.3708172999778817,
 0.4167223022767101,
 0.7875310643666845,
 0.6402265375216425,
 1.0,
 0.9590227894286765,
 0.5672965040660786,
 0.669225589208008,
 0.6712655876989647,
 1.0,
 1.0,
 0.6004927869678728,
 0.4287192354481586,
 0.4833362700818355,
 0.4149257765581974,
 0.0,
 0.7142374013063515,
 0.3836717617877284,
 1.0,
 0.47063561866344156,
 0.8231442177994511,
 0.6032003828758431,
 0.46667091607767364,
 1.0,
 1.0,
 0.4624246067558745,
 1.0,
 0.7311733908231292,
 1.0,
 0.5188309750255874,
 0.7106569613733147,
 0.653634977323481,
 0.4981189057942748,
 1.0,
 0.644882866092338,
 1.0,
 0.3760895625267727,
 0.40936413754815704,
 0.5697890936098513,
 0.7172731866788266,
 1.0,
 0.4379181871701501,
 0.766224372787391,
 0.41749739903616856,
 0.544106413855936,
 0.4585100202254756,
 0.49564555903465546,
 0.513053138353783,
 0.7469817280896172,
 0.8818678664987086,
 0.5676077385797417,
 0.6747784093406343,
 1.0,
 1.0,
 0.9674999309257897,
 0.35398782023458025,
 0.43971971506189017,
 1.0,
 0.40823234037564426,
 0.657890043324603,
 0.5056635825103538,
 0.6185116059790274,
 0.7145586304370573,
 1.0,
 0.560804601493479,
 1.0,
 0.6384821531542941,
 0.3950604699034371,
 0.33483835715086285,
 0.48836512009715133,
 0.4925637640299217,
 1.0,
 0.5740039637059474,
 0.42760777543782996,
 0.65285247771882,
 1.0,
 1.0,
 0.5609591362349559,
 0.8179410904122447,
 0.9782026154827215,
 0.5335555313378926,
 0.5753412882630622,
 0.7953503687512697,
 0.8615930825977327,
 0.47783090350512436,
 0.3973845344399309,
 0.5625346102989973,
 0.7903996216981084,
 1.0,
 1.0,
 1.0,
 0.46547433239637803,
 0.47911695766763174,
 0.5647313667234439,
 0.5563855345175907,
 0.4205284235786236,
 0.3629923626934039,
 0.5204089483097455,
 1.0,
 0.8283605508760922,
 1.0,
 1.0,
 0.6646237834277576,
 0.4094936996711793,
 1.0,
 0.639628997395614,
 0.7702807643126665,
 0.6564513300175475,
 0.40520145758472825,
 0.8451673660649642,
 0.5524227246711935,
 0.47181461530987956,
 0.8742294315031187,
 0.45287681102791755,
 0.9930951912408233,
 0.6038674763031006,
 0.0,
 1.0,
 1.0,
 0.6229147429247462,
 1.0,
 0.49051918727726973,
 0.7277229774756063,
 0.5122956068725062,
 0.6844351360997556,
 0.6213718354033771,
 0.5539876844749048,
 0.5691596420297487,
 1.0,
 0.5240195956418494,
 0.8490662713960182,
 0.9273056823791095,
 0.0,
 1.0,
 0.9850291950663432,
 0.5728087145021324,
 0.4887205519998108,
 0.7803506590378996,
 0.768577458619881,
 0.6474167038732289,
 0.41420700818074097,
 0.8022626652661514,
 1.0,
 0.7287992984148833,
 0.6898195557163415,
 0.48622499326746665,
 1.0,
 1.0,
 0.5935930088254279,
 0.0,
 0.39762956239136527,
 0.7211474248629797,
 1.0,
 0.5211570320040639,
 0.6642447594241467,
 1.0,
 0.6733142369467493,
 1.0,
 0.44375165106131637,
 0.5359471554769657,
 0.45470207118607475,
 1.0,
 0.7495788051859837,
 0.49121244157743704,
 1.0,
 0.8126279471569627,
 0.4837625274023227,
 0.6488258734351189,
 0.7785176228219506,
 0.5033333963352806,
 0.4618705882482386,
 0.7203949432125477,
 1.0,
 0.6330666544224423,
 0.49425772778845734,
 0.4707292553273878,
 0.5481763427327304,
 0.5473192768353627,
 1.0,
 0.4761002472169184,
 0.9094416883187864,
 0.6819265381552507,
 0.4482271470058894,
 0.7471824565384846,
 0.45701538546666504,
 0.583207838636641,
 0.5969965437409817,
 1.0,
 0.37731981567777134,
 0.8226255383482552,
 0.42534823469424116,
 0.8476598687483909,
 0.7175618904871519,
 0.49529160605413264,
 1.0,
 0.5888837401523302,
 1.0,
 0.8720526026958627,
 0.42944781725270686,
 0.4267340942576164,
 0.834979288002782,
 0.5800590567527691,
 0.729200408705406,
 0.3554748757138559,
 0.9041169097802599,
 0.7805308174978886,
 1.0,
 0.6792047633948195,
 0.5356733706218765,
 1.0,
 0.40650395679405277,
 0.5497519283517309,
 0.5760451967771127,
 0.4921306396916664,
 1.0,
 0.6919206761960913,
 1.0,
 1.0,
 0.7835229263048766,
 0.42632175322609844,
 0.4547317929276938,
 0.0,
 0.6078901795814742,
 0.9483772325563029,
 0.4333070334339854,
 0.5471148726627174,
 0.8809588475831186,
 1.0,
 0.6760809598634556,
 0.9665986348462527,
 0.5075783506422834,
 0.7700718455290629,
 0.5491252407545669,
 0.883579621209495,
 0.42312776386107775,
 1.0,
 1.0,
 0.6327564157572022,
 0.47432723749660516,
 0.42987607410840123,
 1.0,
 0.982832858933149,
 1.0,
 0.9525774784710022,
 0.7770646579394164,
 1.0,
 0.7329435165477554,
 0.9703442391249125,
 0.4639549381163559,
 0.7966070654115659,
 0.4703101734840453,
 0.38602856792248835,
 0.9015063691826362,
 0.40684975755566527,
 0.5837479478386357,
 0.7951722794035798,
 1.0,
 0.765711310740641,
 0.42429160398111215,
 0.563894810210929,
 0.6636170740756615,
 0.991416273369087,
 0.699550284352456,
 0.6978777527209425,
 0.654373941628242,
 0.6010794311747748,
 0.42205185013235796,
 0.0,
 0.7262203365769131,
 0.6857544612345111,
 0.6101670080737905,
 0.7747086736163784,
 1.0,
 1.0,
 0.8575715996843521,
 0.6389330655700718,
 0.4328915872901742,
 0.9923195900977422,
 0.6250431780697846,
 0.990510063313965,
 1.0,
 1.0,
 0.5433689643202195,
 0.4822299855156291,
 0.5229328994840753,
 0.8124969412873962,
 0.47263407104341704,
 0.7423555263871662,
 0.5706242481279195,
 1.0,
 0.5736955098356418,
 0.9836879344797352,
 0.4461952031912149,
 1.0,
 0.45705211003951746,
 0.7465622165887155,
 0.46058771253845454,
 1.0,
 0.38687658463860564,
 0.33587865390325167,
 0.9756282216664207,
 0.0,
 0.7497456853054676,
 0.7248670290925945,
 0.759694608553463,
 1.0,
 0.3809714549407068,
 0.6293969122894625,
 0.913485095765439,
 0.4028998248650464,
 0.6203227331191064,
 1.0,
 1.0,
 1.0,
 1.0,
 0.4400782522850549,
 0.5217553814687128,
 0.5677010825636095,
 0.5334962836348182,
 1.0,
 0.48887833537187514,
 1.0,
 0.4942462938151117,
 0.7486347424044747,
 1.0,
 0.4528506616816047,
 0.7849348972792669,
 0.3513098760721781,
 0.4222106472014549,
 1.0,
 0.4342940220155081,
 1.0,
 0.5517152725391101,
 0.7449663749687574,
 0.7401582694536737,
 0.7917410068720554,
 0.325067797648658,
 0.6724070204805582,
 0.9813307180518152,
 0.40191011950644107,
 1.0,
 1.0,
 0.4468676432698025,
 0.4635528497826947,
 0.9808075315435272,
 1.0,
 0.0,
 1.0,
 0.7089900424093474,
 0.5902622897496166,
 0.41577811528508324,
 0.4059557071507567,
 1.0,
 0.5616846481697219,
 1.0,
 0.4970398076200286,
 0.6232449154889592,
 0.7732545186484802,
 1.0,
 0.4432331984447495,
 0.6112636551317814,
 1.0,
 0.6753048635621083,
 0.41601216648833744,
 0.8769450250752024,
 0.7917308200475309,
 0.5803996729124659,
 0.33770154035857397,
 0.6718638835802148,
 0.7474193379098912,
 0.5813171336720794,
 0.6663609282143207,
 0.3829584730971125,
 1.0,
 0.6256503317654487,
 1.0,
 0.4722007572701137,
 0.45579156095523465,
 0.813866297688296,
 0.6257765822953785,
 1.0,
 0.7799302128294164,
 1.0,
 0.8455537211434753,
 0.0,
 0.7804743956393678,
 0.48058235588943965,
 0.6209455498751548,
 1.0,
 0.9932621550929992,
 1.0,
 0.37830639014583134,
 0.8083493518014878,
 0.5036737935857291,
 1.0,
 0.4710933856290556,
 0.483087015106131,
 0.7172963319117927,
 0.5571221383985341,
 1.0,
 0.48627831094504065,
 0.6591296006550155,
 0.46287208010510456,
 0.40991219817602664,
 0.5341717657906705,
 0.716546170718629,
 0.4654772581536226,
 0.5811904884092733,
 0.4345523434338778,
 0.8283605508760922,
 0.37281624111503275,
 1.0,
 1.0,
 0.35554629784886327,
 0.8241272373026679,
 0.4531119382540392,
 0.39287599495342296,
 1.0,
 1.0,
 0.5510764378329982,
 0.3508916569234984,
 0.4922624981089117,
 0.0,
 0.3433979480536627,
 0.5738378018908322,
 0.43430701781996034,
 0.3664324884516323,
 0.37469769009997933,
 0.0,
 0.987914800609386,
 1.0,
 0.32546618753516254,
 0.9227175709163464,
 0.4224929266714468,
 0.734360553908565,
 1.0,
 0.504438995143308,
 0.5775723537326403,
 0.5691309604844405,
 0.7513071662996896,
 0.6137406822321212,
 0.6958955597820009,
 1.0,
 ...]

In [27]:
df_min.shape

NameError: name 'df_min' is not defined

In [28]:
df_min = pd.Series(min_list,
              name="min")
df_min = df_min.to_frame()

df_max = pd.Series(max_list,
              name="max")
df_max = df_max.to_frame()

df_median = pd.Series(med_list,
              name="median")
df_median = df_median.to_frame()

In [29]:
df_median

         median
0      1.000000
1      0.468563
2      0.260455
3      1.000000
4      0.158462
...         ...
96939  0.439050
96940  1.000000
96941  0.228789
96942  0.670377
96943  0.246471

[96944 rows x 1 columns]

In [30]:
df_final = pd.concat([df_data, df_min, df_max, df_median], axis=1)

In [31]:
df_final

,text,label,doc_len,upper_count,punct_count,stop_count,min,max,median
0,they,np,1,0,0,1,1.000000,1.000000,1.000000
1,PhD training in simulation: NATCOR,title,6,1,1,2,0.105596,0.740951,0.468563
2,Effect of SLCO1B1 Polymorphisms on Rifabutin P...,title,14,1,1,5,0.055986,0.445462,0.260455
3,methodology,np,1,0,0,0,1.000000,1.000000,1.000000
4,A randomized controlled trial of the efficacy ...,title,34,1,1,8,0.025805,0.380889,0.158462
...,...,...,...,...,...,...,...,...,...
96939,Profitability of Canadian- Versus U.S.-control...,title,6,0,0,1,0.076646,0.509872,0.439050
96940,neutropenia,np,1,0,0,0,1.000000,1.000000,1.000000
96941,"Multidisciplinary Essays. (Book Reviews: Mind,...",title,25,0,7,12,0.045121,0.556299,0.228789
96942,Major bleeding,np,2,0,0,0,0.445445,0.895309,0.670377
96943,Efficacy and Feasibility of Functional Upper E...,title,18,0,1,5,0.050789,0.413137,0.246471

In [32]:
normalized_df_len=(df_final['doc_len']-df_final['doc_len'].min())/(df_final['doc_len'].max()-df_final['doc_len'].min())

In [33]:
normalized_df_upper_count=(df_final['upper_count']-df_final['upper_count'].min())/(df_final['upper_count'].max()-df_final['upper_count'].min())

In [34]:
normalized_df_punct_count=(df_final['punct_count']-df_final['punct_count'].min())/(df_final['punct_count'].max()-df_final['punct_count'].min())

In [35]:
normalized_df_stop_count=(df_final['stop_count']-df_final['stop_count'].min())/(df_final['stop_count'].max()-df_final['stop_count'].min())

In [36]:
df = pd.concat([normalized_df_len, normalized_df_upper_count, normalized_df_punct_count, normalized_df_stop_count,df_final['min'].to_frame(), df_final['max'].to_frame(), df_final['median'].to_frame() ], axis=1)

In [37]:
#df_features.to_csv('features.csv')

NameError: name 'df_features' is not defined

In [38]:
df_final['label'].to_frame().to_csv('label.csv')

In [39]:
df.loc[:,~df.columns.duplicated()].to_csv('features.csv', index= False)

In [40]:
df.to_csv('features.csv', index= False)

##  Test data feature extraction

In [2]:
data_pred = pd.read_csv('etd_records_v5.csv')
data_pred

,id,title,author,year,university,degree,advisor,department
0,2209,"Urban Form, Wind, Comfort, and Sustainability:...","Kim, Hyungkyoo",2014,"University of California, Berkeley",Doctor Of Philosophy,"Macdonald, Elizabeth;",City And Regional Planning
1,2294,"Movement, Abundance Patterns, and Foraging Eco...","Hofmeister, Jennifer Krista Kaulalani",2015,"University of California, Berkeley",Doctor Of Philosophy,"Caldwell, Roy L;",NaN
2,3735,Regulation of Form in Multicellular Choanoflag...,"Larson, Benjamin Timothy",2019,"University of California, Berkeley",Doctor Of Philosophy,"King, Nicole;Hallatschek, Oskar;",Computational And Genomic Biology
3,4255,Attacks on Emerging Architectures,"Hanna, Steven Craig",2012,"University of California, Berkeley",Doctor Of Philosophy,"Song, Dawn;",Computer Science
4,4485,Study of Laser Melted Liquids and of Interfaci...,"Hull, Christopher James",2019,"University of California, Berkeley",Doctor Of Philosophy,"Saykally, Rich;",Chemistry
...,...,...,...,...,...,...,...,...
494,279281,Metaphor: A communication tool,"Patel, Alpesh R.",NaN,Texas Tech University,Bachelor of Architecture,NaN,Architecture
495,320921,The rationalization of a system for the manufa...,"Eflin, Robert Dean",NaN,Rice University,Master of Architecture,NaN,Architecture
496,277909,The Lubbock Daily Times,"Van Dine, William A. Jr.",NaN,Texas Tech University,Bachelor of Architecture,NaN,Architecture
497,275021,Altruistic civic architecture through selected...,"Ritchie, Blaik",NaN,Texas Tech University,Bachelor of Architecture,NaN,Architecture
498,318345,Making waste public,"Gambetta, Curt",NaN,Rice University,Master of Architecture,"El-Dahdah, Fares",Architecture

In [3]:
data_pred = data_pred.drop(['id', 'author', 'author', 'year', 'university', 'degree', 'advisor','department'], axis=1)

In [4]:
data_pred

                                                 title
0    Urban Form, Wind, Comfort, and Sustainability:...
1    Movement, Abundance Patterns, and Foraging Eco...
2    Regulation of Form in Multicellular Choanoflag...
3                    Attacks on Emerging Architectures
4    Study of Laser Melted Liquids and of Interfaci...
..                                                 ...
494                     Metaphor: A communication tool
495  The rationalization of a system for the manufa...
496                            The Lubbock Daily Times
497  Altruistic civic architecture through selected...
498                                Making waste public

[499 rows x 1 columns]

In [5]:
data_pred.to_csv('titles.csv', index = None)

In [78]:
data_pred['label'] = np.nan
data_pred = data_pred.fillna("title")

In [81]:
data_pred = data_pred.rename(columns={"title": "text"})
data_pred['label'].to_frame().to_csv('label_pred.csv')

In [50]:
tqdm.pandas()

In [51]:
data_pred['doc_len'] = data_pred['text'].apply(lambda words: len(word_tokenize(str(words))))

In [52]:
data_pred = data_pred.dropna().reset_index(drop=True)

In [53]:
def capital_apply_df(df):
    df['upper_count'] = df['text'].apply(lambda x:get_capital_count(x))
    return df

In [61]:
def punct_count_apply_df(df):
    df['punct_count'] = df['text'].apply(lambda x:get_punctuation_counts(x))
    return df

def parallelize_dataframe(df, func, n_cores=40):
    df_split = np.array_split(df, n_cores)
    pool = Pool(n_cores)
    df = pd.concat(pool.map(func, df_split))
    pool.close()
    pool.join()
    return df

In [62]:
def stop_word_count_apply_df(df):
    df['stop_count'] = df['text'].apply(lambda x:stop_word_count(x))
    return df

In [63]:
data_pred = parallelize_dataframe(data_pred, capital_apply_df)

In [64]:
data_pred = parallelize_dataframe(data_pred, punct_count_apply_df)

In [65]:
data_pred = parallelize_dataframe(data_pred, stop_word_count_apply_df)

In [66]:
data_pred

,text,doc_len,upper_count,punct_count,stop_count
0,"Urban Form, Wind, Comfort, and Sustainability:...",14,0,4,5
1,"Movement, Abundance Patterns, and Foraging Eco...",17,0,3,6
2,Regulation of Form in Multicellular Choanoflag...,13,0,0,5
3,Attacks on Emerging Architectures,4,0,0,1
4,Study of Laser Melted Liquids and of Interfaci...,12,0,0,4
...,...,...,...,...,...
494,Metaphor: A communication tool,5,1,1,1
495,The rationalization of a system for the manufa...,13,0,0,6
496,The Lubbock Daily Times,4,0,0,0
497,Altruistic civic architecture through selected...,7,0,0,1
498,Making waste public,3,0,0,0

In [67]:
tf_idf = vectorizer.transform(data_pred['text'])

In [68]:
min_list = []
max_list = []
med_list = []

for i in tqdm(tf_idf):
    a = i.toarray()[0]
    try:
        min_list.append(np.min(a[np.nonzero(a)]))
        max_list.append(np.max(a[np.nonzero(a)]))
        med_list.append(np.median(a[np.nonzero(a)]))
    except:
        min_list.append(0.0)
        max_list.append(0.0)
        med_list.append(0.0)

499it [00:00, 559.13it/s]

In [69]:
df_min = pd.Series(min_list,
              name="min")
df_min = df_min.to_frame()

df_max = pd.Series(max_list,
              name="max")
df_max = df_max.to_frame()

df_median = pd.Series(med_list,
              name="median")
df_median = df_median.to_frame()

In [70]:
normalized_df_len=(data_pred['doc_len']-data_pred['doc_len'].min())/(data_pred['doc_len'].max()-data_pred['doc_len'].min())

normalized_df_upper_count=(data_pred['upper_count']-data_pred['upper_count'].min())/(data_pred['upper_count'].max()-data_pred['upper_count'].min())

normalized_df_punct_count=(data_pred['punct_count']-data_pred['punct_count'].min())/(data_pred['punct_count'].max()-data_pred['punct_count'].min())
normalized_df_stop_count=(data_pred['stop_count']-data_pred['stop_count'].min())/(data_pred['stop_count'].max()-data_pred['stop_count'].min())

In [71]:
df_pred_final = pd.concat([normalized_df_len, normalized_df_upper_count, normalized_df_punct_count, normalized_df_stop_count,df_min['min'].to_frame(), df_max['max'].to_frame(), df_median['median'].to_frame() ], axis=1)

In [72]:
df_pred_final.to_csv('pred_features.csv', index=False)

In [73]:
!head pred_features.csv

doc_len,upper_count,punct_count,stop_count,min,max,median
0.32432432432432434,0.0,0.6666666666666666,0.35714285714285715,0.06064969578958504,0.44252716138738984,0.32558457101839633
0.40540540540540543,0.0,0.5,0.42857142857142855,0.03765046824132918,0.7809246595140266,0.19920419749895057
0.2972972972972973,0.0,0.0,0.35714285714285715,0.05752577915886868,0.5354872137688079,0.2392530356641635
0.05405405405405406,0.0,0.0,0.07142857142857142,0.13634984473142972,0.6395652560384795,0.5321135586624239
0.2702702702702703,0.0,0.0,0.2857142857142857,0.05922407362929875,0.4725474316413063,0.31414328209608916
0.6486486486486487,0.05,0.16666666666666666,0.35714285714285715,0.02710414525977461,0.6336835281860314,0.15143355510593806
0.2972972972972973,0.0,0.0,0.2857142857142857,0.04838580728176038,0.46095945268815647,0.3030301159630567
0.21621621621621623,0.0,0.0,0.14285714285714285,0.06702545356451044,0.5407048765022479,0.3200914875842151
0.35135135135135137,0.0,0.0,0.2857142857142857,0.04272640538060949,0.385510054019234,0.2383657029594907

In [74]:
data_pred

,text,doc_len,upper_count,punct_count,stop_count
0,"Urban Form, Wind, Comfort, and Sustainability:...",14,0,4,5
1,"Movement, Abundance Patterns, and Foraging Eco...",17,0,3,6
2,Regulation of Form in Multicellular Choanoflag...,13,0,0,5
3,Attacks on Emerging Architectures,4,0,0,1
4,Study of Laser Melted Liquids and of Interfaci...,12,0,0,4
...,...,...,...,...,...
494,Metaphor: A communication tool,5,1,1,1
495,The rationalization of a system for the manufa...,13,0,0,6
496,The Lubbock Daily Times,4,0,0,0
497,Altruistic civic architecture through selected...,7,0,0,1
498,Making waste public,3,0,0,0